# -*- coding: utf-8 -*-
"""CV_CO1_AT1_Q10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KYJgGebrAPZEabCIuHwDGZ3MY9AljBIe
"""

# ==========================================================
# Q: Effect of Sampling and Image Formation on Object Visibility
# Google Colab Compatible
# ==========================================================

import cv2
import numpy as np
import matplotlib.pyplot as plt

# ----------------------------------------------------------
# Step 1: Create a high-resolution image
# ----------------------------------------------------------

img = np.zeros((200, 200), dtype=np.uint8)

# Draw the letter 'A'
cv2.putText(img, 'A', (40, 160),
            cv2.FONT_HERSHEY_SIMPLEX,
            4, 255, 8)

# ----------------------------------------------------------
# Step 2: Simulate Low Sampling (Low Resolution)
# ----------------------------------------------------------

# Reduce resolution
low_res = cv2.resize(img, (20, 20), interpolation=cv2.INTER_AREA)

# Enlarge again
upscaled = cv2.resize(low_res, (200, 200),
                      interpolation=cv2.INTER_LINEAR)

# ----------------------------------------------------------
# Step 3: Simulate Poor Image Formation (Blur)
# ----------------------------------------------------------

blurred = cv2.GaussianBlur(upscaled, (9,9), 0)

# ----------------------------------------------------------
# Step 4: Display Results
# ----------------------------------------------------------

plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(img, cmap='gray')
plt.title("High Resolution")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(upscaled, cmap='gray')
plt.title("Low Sampling")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(blurred, cmap='gray')
plt.title("Blurred Image Formation")
plt.axis("off")

plt.tight_layout()
plt.show()

# ----------------------------------------------------------
# Observation
# ----------------------------------------------------------

print("Observation:")
print("1. High-resolution image clearly shows the object.")
print("2. Low sampling reduces the number of pixels, causing loss of detail.")
print("3. Upscaling cannot recover the lost information.")
print("4. Blur further reduces visibility by spreading light across neighboring pixels.")

print("\nConclusion:")
print("Object visibility depends on both adequate sampling (high spatial resolution)")
print("and proper image formation (good focus and minimal blur).")