# -*- coding: utf-8 -*-
"""CV_CO1_AT1_Q07

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14WDCP-0k6Rm2xHyXaTmHG2SXa50LhAbT
"""

# ==========================================================
# Quantization in Grayscale Images
# Google Colab Compatible
# ==========================================================

# Install OpenCV
!pip install opencv-python -q

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# ----------------------------------------------------------
# Upload Image
# ----------------------------------------------------------
print("Upload a grayscale or color image")

uploaded = files.upload()

filename = list(uploaded.keys())[0]

# Read image in grayscale
img = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)

if img is None:
    print("Error: Image not loaded.")
else:

    # ------------------------------------------------------
    # Quantization Function
    # ------------------------------------------------------
    def quantize(image, levels):
        step = 256 // levels
        quantized = (image // step) * step
        return quantized.astype(np.uint8)

    # Different Quantization Levels
    img_256 = img                      # Original (256 levels)
    img_64 = quantize(img, 64)
    img_16 = quantize(img, 16)
    img_8 = quantize(img, 8)
    img_4 = quantize(img, 4)

    # ------------------------------------------------------
    # Display Results
    # ------------------------------------------------------
    plt.figure(figsize=(15,8))

    plt.subplot(2,3,1)
    plt.imshow(img_256, cmap='gray')
    plt.title("256 Gray Levels")
    plt.axis("off")

    plt.subplot(2,3,2)
    plt.imshow(img_64, cmap='gray')
    plt.title("64 Gray Levels")
    plt.axis("off")

    plt.subplot(2,3,3)
    plt.imshow(img_16, cmap='gray')
    plt.title("16 Gray Levels")
    plt.axis("off")

    plt.subplot(2,3,4)
    plt.imshow(img_8, cmap='gray')
    plt.title("8 Gray Levels")
    plt.axis("off")

    plt.subplot(2,3,5)
    plt.imshow(img_4, cmap='gray')
    plt.title("4 Gray Levels")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

    # ------------------------------------------------------
    # Conclusion
    # ------------------------------------------------------
    print("\nObservation:")
    print("• 256 Levels → Highest image quality and detail.")
    print("• 64 Levels → Slight loss of detail.")
    print("• 16 Levels → Noticeable banding begins.")
    print("• 8 Levels → Significant detail loss.")
    print("• 4 Levels → Severe banding and poor image quality.")