# -*- coding: utf-8 -*-
"""CV_CO1_AT1_Q05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tizoQqCEqShrbc0ATiRKf-m_ynbYMxjd
"""

pip install opencv-python

# Install OpenCV (if needed)
!pip install opencv-python

import cv2
import matplotlib.pyplot as plt
from google.colab import files

# Upload a surveillance video (e.g., surveillance.mp4)
uploaded = files.upload()

# Get uploaded file name
video_path = list(uploaded.keys())[0]

# Open the uploaded video
cap = cv2.VideoCapture(video_path)

# Background subtractor (Mid-Level CV)
bg_subtractor = cv2.createBackgroundSubtractorMOG2()

# Read the first frame
ret, frame = cap.read()

if ret:
    # -------------------------------
    # Low-Level Computer Vision
    # -------------------------------
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5, 5), 0)
    enhanced = cv2.equalizeHist(blur)

    # -------------------------------
    # Mid-Level Computer Vision
    # -------------------------------
    foreground = bg_subtractor.apply(frame)
    edges = cv2.Canny(enhanced, 50, 150)

    # Find moving object contours
    contours, _ = cv2.findContours(foreground, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # -------------------------------
    # High-Level Computer Vision
    # -------------------------------
    for contour in contours:
        if cv2.contourArea(contour) > 500:
            x, y, w, h = cv2.boundingRect(contour)
            cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
            cv2.putText(frame, "Moving Object", (x, y-10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,255,0), 2)

    # Convert BGR to RGB for Matplotlib
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    # Display results
    plt.figure(figsize=(12,8))

    plt.subplot(2,2,1)
    plt.imshow(frame_rgb)
    plt.title("Original Surveillance")
    plt.axis("off")

    plt.subplot(2,2,2)
    plt.imshow(enhanced, cmap='gray')
    plt.title("Enhanced Image (Low-Level CV)")
    plt.axis("off")

    plt.subplot(2,2,3)
    plt.imshow(foreground, cmap='gray')
    plt.title("Motion Detection (Mid-Level CV)")
    plt.axis("off")

    plt.subplot(2,2,4)
    plt.imshow(edges, cmap='gray')
    plt.title("Edge Detection (Mid-Level CV)")
    plt.axis("off")

    plt.show()

else:
    print("Error: Unable to read the video.")

cap.release()