# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ktoI9XinCOmkN5rgeYVr7aP2C44tKnQ3
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Create a smooth grayscale gradient image
img = np.tile(np.linspace(0, 255, 256, dtype=np.uint8), (256, 1))

# -----------------------------
# Pixel Resolution Demonstration
# -----------------------------
# Reduce image size (sampling)
low_pixel = cv2.resize(img, (64, 64), interpolation=cv2.INTER_LINEAR)

# Resize back for viewing
low_pixel = cv2.resize(low_pixel, (256, 256), interpolation=cv2.INTER_NEAREST)

# -----------------------------
# Intensity Resolution Demonstration
# -----------------------------
# Convert 8-bit (256 shades) to 3-bit (8 shades)
quantized = np.floor(img / 32) * 32
quantized = quantized.astype(np.uint8)

# -----------------------------
# Display Results
# -----------------------------
plt.figure(figsize=(10,8))

plt.subplot(2,2,1)
plt.imshow(img, cmap='gray')
plt.title("Original Image")
plt.axis('off')

plt.subplot(2,2,2)
plt.imshow(low_pixel, cmap='gray')
plt.title("Low Pixel Resolution")
plt.axis('off')

plt.subplot(2,2,3)
plt.imshow(img, cmap='gray')
plt.title("8-bit (256 Gray Levels)")
plt.axis('off')

plt.subplot(2,2,4)
plt.imshow(quantized, cmap='gray')
plt.title("3-bit (8 Gray Levels)")
plt.axis('off')

plt.tight_layout()
plt.show()